FROM golang:1.22-alpine AS builder
RUN apk add --no-cache git ca-certificates
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /store ./cmd/store/

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /store /store
USER nonroot:nonroot
EXPOSE 5454 9090
ENTRYPOINT ["/store"]
